version: 2
project_name: go-music-dl
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go install github.com/tc-hib/go-winres@latest
    - go-winres make --in ./winres/winres.json --out ./cmd/music-dl/rsrc
builds:
  - id: nowin
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    main: ./cmd/music-dl
    binary: music-dl
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w
  - id: win
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - windows
    goarch:
      - amd64
    main: ./cmd/music-dl
    binary: music-dl
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w

checksum:
  name_template: "go-music-dl_checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - fix typo
      - Merge pull request
      - Merge branch
      - Merge remote-tracking
      - go mod tidy

archives:
  - id: nowin
    builds:
      - nowin
    name_template: "go-music-dl_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        formats: zip
  - id: win
    builds:
      - win
    name_template: "go-music-dl_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        formats: zip

nfpms:
  - license: AGPL 3.0
    homepage: https://github.com/guohuiyuan/go-music-dl
    file_name_template: "go-music-dl_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    formats:
      - deb
      - rpm
    maintainer: guohuiyuan
